#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a lemonbar layer=below
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a pavucontrol state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^10' focus=off follow=false

#colors
#source the colors.
. "${HOME}/.cache/wal/colors.sh"

#Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

wal --theme sexy-hund -a "60"

# Launch Polybar
$HOME/.config/polybar/launch.sh
