# Visit kitty website for more config options: https://sw.kovidgoyal.net/kitty/conf

# Fonts

font_family 3270SemiNarrow Nerd Font Mono
bold_font 3270SemiNarrow Nerd Font Mono
italic_font 3270SemiNarrow Nerd Font Mono
bold_italic_font 3270SemiNarrow Nerd Font Mono

font_size 18.0

# - Use additional nerd symbols
# See https://github.com/be5invis/Iosevka/issues/248
# See https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
# Seti-UI + Custom
symbol_map U+E5FA-U+E62B Symbols Nerd Font
# Devicons
symbol_map U+E700-U+E7C5 Symbols Nerd Font
# Font Awesome
symbol_map U+F000-U+F2E0 Symbols Nerd Font
# Font Awesome Extension
symbol_map U+E200-U+E2A9 Symbols Nerd Font
# Material Design Icons
symbol_map U+F500-U+FD46 Symbols Nerd Font
# Weather
symbol_map U+E300-U+E3EB Symbols Nerd Font
# Octicons
symbol_map U+F400-U+F4A8,U+2665,U+26A1,U+F27C Symbols Nerd Font
# Powerline Extra Symbols
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CC-U+E0D2,U+E0D4 Symbols Nerd Font
# IEC Power Symbols
symbol_map U+23FB-U+23FE,U+2b58 Symbols Nerd Font
# Font Logos
symbol_map U+F300-U+F313 Symbols Nerd Font
# Pomicons
symbol_map U+E000-U+E00D Symbols Nerd Font


# Define how kitty handles bidirectional scripts
force_ltr no

disable_ligatures always 


adjust_line_height 0
adjust_column_width 0

adjust_baseline 0


# Cursor
cursor #cccccc

cursor_text_color #111111

cursor_shape block

cursor_beam_thickness 1.5

cursor_underline_thickness 2.0

cursor_blink_interval -1

cursor_stop_blinking_after 0


# Scrollback

scrollback_lines 2000

scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

scrollback_pager_history_size 0

scrollback_fill_enlarged_window no

wheel_scroll_multiplier 5.0

touch_scroll_multiplier 1.0


# Moue

mouse_hide_wait 3.0

url_color #0087bd

url_style curly

open_url_with default

url_prefixes http https file ftp gemini irc gopher mailto news git

detect_urls yes

copy_on_select no

strip_trailing_spaces never

select_by_word_characters @-./_~?&=%+#

click_interval -1.0

focus_follows_mouse no

pointer_shape_when_grabbed arrow

default_pointer_shape beam

pointer_shape_when_dragging beam


# Terminal bell
enable_audio_bell no

visual_bell_duration 0


# Color scheme

foreground #ffffff
background #000000

background_opacity 0.6

background_image none


# Keyboard shortcuts

# kitty_mod ctrl_shift

clear_all_shortcuts no

#  Clipboard

map kitty_mod+c copy_to_clipboard

map kitty_mod+v paste_from_clipboard

map kitty_mod+s paste_from_selection

map kitty_mod+o pass_selection_to_program

#  Window management

map kitty_mod+enter new_window

map kitty_mod+n new_os_window

map kitty_mod+w close_window
map kitty_mod+] next_window
map kitty_mod+[ previous_window
map kitty_mod+f move_window_forward
map kitty_mod+b move_window_backward
map kitty_mod+` move_window_to_top
map kitty_mod+r start_resizing_window
map kitty_mod+1 first_window
map kitty_mod+2 second_window
map kitty_mod+3 third_window
map kitty_mod+4 fourth_window
map kitty_mod+5 fifth_window
map kitty_mod+6 sixth_window
map kitty_mod+7 seventh_window
map kitty_mod+8 eighth_window
map kitty_mod+9 ninth_window
map kitty_mod+0 tenth_window

#  Tab management

map kitty_mod+right next_tab
map kitty_mod+left  previous_tab
map kitty_mod+t     new_tab
map kitty_mod+q     close_tab
map shift+cmd+w     close_os_window
map kitty_mod+.     move_tab_forward
map kitty_mod+,     move_tab_backward
map kitty_mod+alt+t set_tab_title

#  Layout management

map kitty_mod+l next_layout

#  Font sizes

map kitty_mod+equal     change_font_size all +2.0
map kitty_mod+minus     change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0


