#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor VIRTUAL1 -d I II III IV V
bspc monitor eDP1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^10' follow=off

picom -b --config ~/.config/picom/picom.conf

feh --bg-max --randomize ~/images/WLOP/* &

PATH=$PATH:$HOME/.myscripts

# Unmute audio
amixer -c 0 sset "Auto-Mute Mode" Disabled
