#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# I recommend you to take a look into my scripts below to understand the effects
# and modify config values to customize it.

# Configure external monitor if is connected (only supports two monitors).
bash $HOME/.config/bspwm/xrandr_dual_monitor.sh

# Using my script to configure desktops
bash $HOME/.config/bspwm/bspwm_dual_monitor_script.sh


# Default desktop setup for one monitor. 
# You could use other characters for desktop symbols (e.g. a b c 💪)
# Uncomment the line below if you are just using one monitor.
# bspc monitor -d 1 2 3 4 5 6 7 8 9 💪

bspc config border_width         2
bspc config window_gap         	3
bspc config top_padding			0

# I need a bright border color because I'm blind
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Always launch discord at tenth desktop
bspc rule -a discord desktop='^10' 
bspc rule -a Gimp desktop='^8' state=floating follow=on

# ---Autostart---
# Launch Polybar
bash $HOME/.config/polybar/launch.sh

# Set background image (which uses background image from the previos session)
~/.fehbg &
